### ISSUE TITLE
We need some Bootstrap CSS classes from the core

### ISSUE THREAD

**Issue by juergen-venne** [TYPO3-Initiatives/digital-asset-management#19]
To render the breadcrumb properly we want to use bootstrap classes. But these classes and CSS are missing. This destroyes the view for now.
Should we create our own CSS or should the core delivery the missing classes?

**Comment by jokumer** [comment]
In my opinion, this question should be addressed to the component Backend Client-side development according to the newly announced TYPO3 Core development workflow.

**Comment by benjaminkott** [comment]
i will close that issue
